/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/airplane/airplane.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/airplane.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Torus001_1.geometry} material={materials['07___Default']} />

    </group>
  )
}

useGLTF.preload('/airplane.glb')
